---
title: "Protocolo de Muestreo para Vida Silvestre"
description: |
  Grilla de referencia
author:
  - name: Manuel Spínola 
    url: https://example.com/norajones
    affiliation: ICOMVIS - UNA
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(rio)
library(glue)
library(sf)
library(raster)
library(rgeoboundaries)
library(mapview)
```


```{r, include=FALSE}
df <- import("grilla.xlsx")
```


```{r, include=FALSE}
df$celda <- paste(df$letra,"-",df$num)
```

```{r, include=FALSE}
color1 <- rep(c("A", "B"), each = 4, times = 2)
```

```{r, include=FALSE}
color2 <- rep(c("B", "A"), each = 4, times = 2)
```

```{r, include=FALSE}
color3 <- rep(c("A", "B"), each = 4, times = 2)
```

```{r, include=FALSE}
color4 <- rep(c("B", "A"), each = 4, times = 2)
```

```{r, include=FALSE}
df$color <- c(color1, color2, color3, color4)
```


```{r, include=FALSE}
df
```


```{r, include=FALSE}
cr <- st_as_sf(getData('GADM', country='CRI', level=0))
```

```{r, include=FALSE}
plot(cr["GID_0"])
```

```{r, include=FALSE}
cr_5367 <- st_transform(cr, crs = 5367)
```


```{r, include=FALSE}
cr_gb <- gb_adm0("costa rica", type = "hpscu")
plot(st_geometry(cr_gb))
```

```{r, echo=FALSE}
ggplot() +
  theme_minimal() +
  geom_sf(data = cr_5367, aes(fill = GID_0), fill = "blue", alpha = 0.4) + coord_sf(datum = st_crs(5367))
```

### Grilla de referencia

El territorio terrestre de Costa Rica se divide en una grilla de referencia de 8km x 8km. 

```{r, include=FALSE}
grilla_cr_5367 <- st_make_grid(cr_5367,
                          cellsize = 8000,
                          crs = st_crs(cr_5367),
                          what = "polygons",
                          square = TRUE)
```


```{r, include=FALSE}
plot(grilla_cr_5367, col = 'white')
plot(st_geometry(cr_5367), col = "blue", add = T)
```

```{r, include=FALSE}
grilla_cr_5367
```


```{r, echo=FALSE}
ggplot() +
  theme_minimal() +
  geom_sf(data = grilla_cr_5367, color = "grey", fill = "white") +
  geom_sf(data = cr_5367, aes(fill = GID_0), fill = "blue", alpha = 0.4) +
  coord_sf(datum = st_crs(5367))
```

### Detalle de cada celda de 8k x 8km

Cada celda  de 8km x 8km está compuesta a su vez por tétradas de 4 celdas de 1 km organizadas en celdas de 2km x 2km. Hay 16 tétradas en cada celda de 8km x 8km.

```{r, echo = FALSE}
ggplot(df, aes(x, y)) +
  theme_minimal() +
  geom_tile(aes(fill = color), color = "black") +
  geom_text(aes(label = celda), color = "black") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("grey", "white")) +
  xlab("8 km") +
  ylab("8 km") +
  coord_equal()
```








